# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regalos',
            name='fotoRegalo',
            field=models.ImageField(upload_to='img/gift'),
        ),
    ]
