# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regaloobtenido',
            name='id_usuarios5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarios'),
        ),
    ]
