# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20170323_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regalos',
            name='id_regalos',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statusregalo',
            name='id_statusRegalo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
