# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deportes',
            fields=[
                ('id_deportes', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('deportes', models.CharField(max_length=50)),
                ('foto_d', models.ImageField(upload_to='img/deportes')),
            ],
        ),
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id_equipos', models.AutoField(primary_key=True, serialize=False)),
                ('equipos', models.CharField(max_length=50)),
                ('foto_e', models.ImageField(upload_to='img/equipos')),
            ],
        ),
        migrations.CreateModel(
            name='ligas',
            fields=[
                ('id_ligas', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ligas', models.CharField(max_length=50)),
                ('foto_l', models.ImageField(upload_to='img/ligas')),
                ('id_deportes1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.deportes')),
            ],
        ),
        migrations.AddField(
            model_name='equipos',
            name='ligas1',
            field=models.ManyToManyField(to='sports.ligas'),
        ),
    ]
