# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20170323_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportes',
            name='foto_d',
            field=models.ImageField(upload_to='img/equipo'),
        ),
    ]
