# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20170323_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportes',
            name='id_deportes',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='id_equipos',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ligas',
            name='id_ligas',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
