# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bonusDiario',
            fields=[
                ('id_bonusDiario', models.IntegerField(primary_key=True, serialize=False)),
                ('seguidilla', models.IntegerField()),
                ('puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='promociones',
            fields=[
                ('id_promocion', models.IntegerField(primary_key=True, serialize=False)),
                ('promocion', models.CharField(max_length=50)),
                ('tipoPromocion', models.CharField(max_length=50)),
                ('puntosObtener', models.IntegerField()),
                ('fotoPromocion', models.ImageField(upload_to='media/img/promotion/')),
            ],
        ),
        migrations.CreateModel(
            name='promoRealizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promocion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promociones')),
                ('id_usuarios6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarios')),
            ],
        ),
    ]
