# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 04:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bonusDiario',
            fields=[
                ('id_bonusDiario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('seguidilla', models.IntegerField()),
                ('puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='promociones',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('promocion', models.CharField(max_length=50)),
                ('tipoPromocion', models.CharField(max_length=50)),
                ('puntosObtener', models.IntegerField()),
                ('fotoPromocion', models.ImageField(upload_to='img/promotion')),
            ],
        ),
        migrations.CreateModel(
            name='promoRealizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promocion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promociones')),
                ('id_usuarios6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
