# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='equiposFavoritos',
            field=models.ManyToManyField(to='sports.equipos'),
        ),
    ]
