# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20170523_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_usuarios',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
