# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170518_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_usuarios',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
