# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuarios_equiposfavoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='banner',
            field=models.ImageField(upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(upload_to='perfil'),
        ),
    ]
