# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170518_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='idusuarios',
            new_name='id_usuarios',
        ),
    ]
