# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170523_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_apellido1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_edperfil1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ediPerfil'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_genero1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.genero'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_natalidad1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.natalidad'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_nivusuario1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.nivelUsuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_nombre1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_pais1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.pais'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_postal1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.postal'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_stusUsario1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.statusUsario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_zhoraria1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.zonaHoraria'),
        ),
    ]
