# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170521_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntos',
            name='id_usuarios2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarios'),
        ),
    ]
