# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 13:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jugadaPorra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='jugadaPote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultadoHPote', models.IntegerField()),
                ('resultadoVPote', models.IntegerField()),
                ('fechaPote', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='jugadas',
            fields=[
                ('id_jugadas', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('puntosJugados', models.IntegerField()),
                ('puntosGanar', models.IntegerField(default=0)),
                ('fechaJugada', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='partidos',
            fields=[
                ('id_partidos', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField()),
                ('home', models.DecimalField(decimal_places=2, max_digits=3)),
                ('empate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('visitante', models.DecimalField(decimal_places=2, max_digits=3)),
                ('puntuacion_h', models.IntegerField(default=0)),
                ('puntuacion_v', models.IntegerField(default=0)),
                ('actualizado', models.IntegerField(default=1)),
                ('id_equiposh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiposh', to='sports.equipos')),
                ('id_equiposv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiposv', to='sports.equipos')),
                ('id_ligas2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ligas')),
            ],
        ),
        migrations.CreateModel(
            name='porra',
            fields=[
                ('id_porra', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombrePorra', models.CharField(max_length=100)),
                ('premioPorra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='porraEquipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partidos4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.partidos')),
                ('id_porra4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.porra')),
            ],
        ),
        migrations.CreateModel(
            name='pote',
            fields=[
                ('id_pote', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombrePote', models.CharField(max_length=50)),
                ('costePote', models.IntegerField()),
                ('premioPote', models.IntegerField()),
                ('id_partidos2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.partidos')),
            ],
        ),
        migrations.CreateModel(
            name='resultadoJugadas',
            fields=[
                ('id_rjugada', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('resultadoJ', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='porraequipos',
            name='id_rjugada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.resultadoJugadas'),
        ),
        migrations.AddField(
            model_name='jugadas',
            name='id_partidos1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.partidos'),
        ),
        migrations.AddField(
            model_name='jugadas',
            name='id_rjugada1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_rjugada1', to='plays.resultadoJugadas'),
        ),
        migrations.AddField(
            model_name='jugadas',
            name='id_usuarios1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jugadas',
            name='jugada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugada', to='plays.resultadoJugadas'),
        ),
        migrations.AddField(
            model_name='jugadapote',
            name='id_pote1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.pote'),
        ),
        migrations.AddField(
            model_name='jugadapote',
            name='id_resultadoPote1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.resultadoJugadas'),
        ),
        migrations.AddField(
            model_name='jugadapote',
            name='id_usuarios10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jugadaporra',
            name='id_jugadaPorra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.resultadoJugadas'),
        ),
        migrations.AddField(
            model_name='jugadaporra',
            name='id_partidos5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.partidos'),
        ),
        migrations.AddField(
            model_name='jugadaporra',
            name='id_porra2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.porra'),
        ),
        migrations.AddField(
            model_name='jugadaporra',
            name='id_usuarios11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
