# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='referidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_referidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_referidos', to=settings.AUTH_USER_MODEL)),
                ('id_usuarios3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuarios3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='seguidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_seguido', to=settings.AUTH_USER_MODEL)),
                ('id_seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_seguidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='statusSeguidor',
            fields=[
                ('id_statusSeguidor', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('statusSeguidor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subReferidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subReferidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_subReferidos', to=settings.AUTH_USER_MODEL)),
                ('id_usuarios9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuarios9', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='seguidores',
            name='id_statusSeguidor1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.statusSeguidor'),
        ),
    ]
