# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='referidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_referidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_referidos', to='users.usuarios')),
                ('id_usuarios3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuarios3', to='users.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='seguidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_seguido', to='users.usuarios')),
                ('id_seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_seguidor', to='users.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='statusSeguidor',
            fields=[
                ('id_statusSeguidor', models.IntegerField(primary_key=True, serialize=False)),
                ('statusSeguidor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subReferidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subReferidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_subReferidos', to='users.usuarios')),
                ('id_usuarios9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuarios9', to='users.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='seguidores',
            name='id_statusSeguidor1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.statusSeguidor'),
        ),
    ]
