# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusseguidor',
            name='id_statusSeguidor',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
